### PR TITLE
Add --speed

### LINKED ISSUE #21: Option args for other asciinema configurables
It would be nice if we could pass option args to asciinema2gif that are supported in the GET request to the https://asciinema.org/api/asciicasts/ resource. e.g. speed, tframe, etc.

This would preclude users from having to figure out the ugly GET request syntax with their desired parameters before running the URL by asciinema2gif. i.e. https://asciinema.org/api/asciicasts/88888?t=4&speed=2

### PR DESCRIPTION
**Pull request by vitorgalvao**
Closes #21.

### CODE REVIEW

**Comment by wong2** [comment]
oh, conflicts after I merged #22

**Comment by vitorgalvao** [comment]
Figured that might happen. It’s now fixed.

**Comment by vitorgalvao** [comment]
This and #22 might warrant a new release so we can [update the formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/asciinema2gif.rb).

**Comment by wong2** [comment]
@vitorgalvao I've made a new release: https://github.com/tav/asciinema2gif/tags

**Comment by vitorgalvao** [comment]
[Submitted](https://github.com/Homebrew/homebrew-core/pull/645).

**Pull request merged**
