### PR TITLE
make it work again

### PR DESCRIPTION
**Pull request by wong2**
overwrite `XMLHttpRequest.prototype.open` to intercept on the data load.
it works for me again, here is the resulting gif:

https://github.com/wong2/pick/blob/master/example/basic.gif

### CODE REVIEW

**Comment by jmaupetit** [comment]
:+1: works like a charm

**Comment by iblech** [comment]
Can confirm that it works like a charm.

I had to increase the number in `sameCount === 3` (in render.js, line 122) to a higher value, else the playback was aborted early. `20` worked fine for me.

**Comment by jonscottclark** [comment]
Please :) Or else we all will just fork it :(

**Comment by techtonik** [comment]
@tav is absent from GitHub, so I unless somebody finds a way to contact him through a different channel, the fork is the only option in short term perspective.

**Comment by tav** [comment]
Hi guys, sorry, only just saw this — thanks for the @mention @techtonik :+1:

I'll take a proper look and apply either this or a related fix later today. And, btw, if any of you would like to be added to the repo as a maintainer, please do let me know. Cheers!

**Comment by wong2** [comment]
@tav I'm interested at maintaining this repo :beer:

**Comment by tav** [comment]
Brilliant idea @wong2, intercepting `XMLHttpRequest.prototype.open`.

Have merged it in and applied a couple of additional fixes including @iblech's `sameCount` fix and changed the URL detection to just `.json` since asciinema have seemingly changed the requested URL since the patch.

It should all be working again — sorry for my delay in applying the various fixes :disappointed:

Thanks @wong2 for volunteering as the new maintainer. I've added you to the repo. Best of luck and please let me know if you ever get bored of it. Thanks!

I've also added a longer overdue credits section thanking the likes of @iblech, and the `.eslintrc` file I use for linting. Let me know if there's anything else you need from me and thanks again guys :beers:

**Comment by wong2** [comment]
:beer:

**Comment by techtonik** [comment]
Awesome to see this fixed. =)

**Pull request merged**
